### ISSUE TITLE
send to bundler request failed; http code: 402

### ISSUE THREAD

**Issue by samsends** [everFinance/goar#28]
Hello, I am trying to use the bundler to upload files but every time I attempt to submit a bundle I receive this error:

`send to bundler request failed; http code: 402`

this is my flow for finalizing:

```golang

	_, err := bm.Wallet.Client.BatchSendItemToBundler(bm.BundleItems)
	if err != nil {
		return err
	}

	bd, err := utils.NewBundle(bm.BundleItems...)
	if err != nil {
		return err
	}

	_, err = bm.Wallet.SendBundleTx(bd.BundleBinary, nil)
	if err != nil {
		return err
	}

```

**Comment by zyjblockchain** [comment]
v1.3.2 has fix bundler tx. 
and the readme also add how to use bundler service
https://github.com/everFinance/goar/tree/v1.3.2#notice

**Comment by zyjblockchain** [comment]
There are two reasons why goar cannot push bundle item to bundler servise
1. Bundler service is now available as a paid service. The bundler item data signature address must be recharged with ar in order to use the bundler service
2. Bundler gateway url changed.

**Comment by zyjblockchain** [comment]
v1.3.2 version has resloved this problem
