### ISSUE TITLE
Sending data more than one chunks fail.

### ISSUE THREAD

**Issue by oday0311** [everFinance/goar#33]
sample 1), data is less than one chunk, will success

func TestWallet_SendDataSpeedUp01(t *testing.T) {
	// arNode := "https://arweave.net"
	// w, err := NewWalletFromPath("./example/testKey.json", arNode) // your wallet private key
	// assert.NoError(t, err)

	//data := []byte("aaa this is a goar test small size file data") // small file
	data := make([]byte, 255*1024)
	for i := 0; i < len(data); i++ {
		data[i] = byte('b' + i)
	}
	tags := []types.Tag{
		{Name: "GOAR", Value: "SMDT"},
	}
	id, err := testWallet.SendDataSpeedUp(data, tags, 50)
	assert.NoError(t, err)
	t.Logf("tx hash: %s", id)
}

==========================

sample 2) data size 10 chunks.  return with the following error: 
             Unable to upload Transaction: 400, <nil>, Transaction verification failed.

func TestWallet_SendDataSpeedUp01(t *testing.T) {
	// arNode := "https://arweave.net"
	// w, err := NewWalletFromPath("./example/testKey.json", arNode) // your wallet private key
	// assert.NoError(t, err)

	//data := []byte("aaa this is a goar test small size file data") // small file
	data := make([]byte, 255*1024*10)
	for i := 0; i < len(data); i++ {
		data[i] = byte('b' + i)
	}
	tags := []types.Tag{
		{Name: "GOAR", Value: "SMDT"},
	}
	id, err := testWallet.SendDataSpeedUp(data, tags, 50)
	assert.NoError(t, err)
	t.Logf("tx hash: %s", id)
}

**Comment by zyjblockchain** [comment]
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/40423181/159440162-7a971a71-8d9e-4fdb-9ef8-e690b5fc1bec.png">
I test about 7.5 MB file for upload to arweave is ok
your case return 400, means your transaction signature verify failed.
please check your tx signature, you can use utils.VerifyTransaction() function to check your sign

**Comment by oday0311** [comment]
I am using the same code and account just change the data part from
data := make([]byte, 255*1024)
to 
data := make([]byte, 255*1024*10), 

can you try this sample?
func TestWallet_SendDataSpeedUp01(t *testing.T) {

**Comment by zyjblockchain** [comment]
> 

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/40423181/159609618-f1ec7266-fb94-4b31-823e-fa01ed2b5223.png">
it is ok

**Comment by dmitrymomot** [comment]
I have the same error. 
@oday0311, how did you solve it?

**Comment by oday0311** [comment]
@dmitrymomot ,  I skip this , I still think there maybe some bug in this, but not that important to me , so I turn to some other place.
