### ISSUE TITLE
Can goar support uploading file with streaming style?

### ISSUE THREAD

**Issue by daqiancode** [everFinance/goar#46]
Current API only support uploading bytes([]byte). It is obviously not good for upload big files(e.g., video files) at same time.
Shall we consider arweave API like S3? 
PutObject(reader io.Reader, objectSize int64, opt PubObjectOption) (PutObjectResult, err error)

Thanks a lot

**Comment by zyjblockchain** [comment]
It is already in development and can be seen in Pull requests

**Comment by zyjblockchain** [comment]
We now support streaming file uploads.
