### ISSUE TITLE
License

### ISSUE THREAD

**Issue by brucexc** [everFinance/goar#60]
Dear author,
Thank you for this great work! I'm wondering if you could indicate the license under which the code in this repository is distributed. This will greatly improve the possibilities of using your work. Thanks a lot!

**Comment by pkieltyka** [comment]
hi all -- any updates on this..? do you mind adding a LICENSE file to the project?

ie. https://github.com/go-chi/chi/blob/master/LICENSE

then its more friendly for developers to actually use the library in real world projects

**Comment by pkieltyka** [comment]
https://github.com/everFinance/goar/commit/eaa4671aaf46628190d4bbdff1ce499bc4408768

thanks for adding the license :)
